### ISSUE TITLE
fix buildfarm deployment branch name

### ISSUE THREAD

**Issue by asierfernandez** [ros-infrastructure/buildfarm_deployment_config#38]
https://github.com/ros-infrastructure/buildfarm_deployment_config/blob/85c9118fec629ba001876a254bf62ed1b84f83d1/reconfigure.bash#L14

I'm trying to set a new clean instance of the buildfarm, but the process chashes because `jenkins-lts-upgrades` branch doesn't exist. 

It seems to me that the correct branch is `jenkins-lts-upgrade` without `s` in the end.

**Comment by nuclearsandwich** [comment]
The changes here were incorporated directly in #37. Thanks for reporting @asierfernandez

**Comment by asierfernandez** [comment]
you are wellcome! I'll be working with the buildfarm internally in our place. I'll try to test as much as I can
