### ISSUE TITLE
The running build.py fails

### ISSUE THREAD

**Issue by Victor-Savu** [ros-infrastructure/buildfarm_deployment_config#7]
Running `python build.py` in a vanilla clone of this repo fails with the following error:

<pre><output truncated for brevity>
[Librarian] Installing tracywebtech-pip/1.3.2 <https://forgeapi.puppetlabs.com>
[Librarian] Executing puppet module install for tracywebtech-pip 1.3.2: puppet module install --version 1.3.2 --target-dir /root/buildfarm_deployment/master/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/tracywebtech-pip/1.3.2 --module_repository https://forgeapi.puppetlabs.com --modulepath /root/buildfarm_deployment/master/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/tracywebtech-pip/1.3.2 --module_working_dir /root/buildfarm_deployment/master/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/tracywebtech-pip/1.3.2 --ignore-dependencies tracywebtech-pip
Running puppet
The command '/bin/sh -c ./reconfigure.bash master' returned a non-zero code: 1
Traceback (most recent call last):
  File "build.py", line 37, in <module>
    subprocess.check_call(cmd.split())
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'master', '.']' returned non-zero exit status 1
</pre>

**Comment by tfoote** [comment]
build.py is an old tool we used for development and is not supported anymore. We've moved away from using docker in docker due to complications. 

Please see the documentation here: https://github.com/ros-infrastructure/buildfarm_deployment for how to setup a buildfarm.
